/** @format */
import Head from 'next/head';
import styles from '../styles/Home.module.scss'; 
import { Counter } from './components/Counter';
import { RepositoryList } from './components/RepositoryList';


export default function Home() {
	return (
		<div className={styles.container}>
			<Head>
				<title>Next Ignite</title>
				<meta name='description' content='Generated by create next app' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			
				<main className={styles.main}>
					{/* <h1 className={styles.title}>
						Hello <a href='#'> World!</a>
					</h1> */}
					
				<RepositoryList />
				<Counter/>
				

					<div className={styles.grid}></div>
				</main>
			

			<footer className={styles.footer}>
				<a
					href='https://gilbertoaleite-portfolio.netlify.app/'
					target='_blank'
					rel='noopener noreferrer'
				>
					Powered by{' '}
					<span className={styles.logo}>
						<p width={72} height={16}>
							Gilberto A Leite
						</p>
					</span>
				</a>
			</footer>
		</div>
	);
}
